set(VIENNACL_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/viennacl")
set(VIENNACL_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/viennacl/install")
set(VIENNACL_CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${VIENNAGRID_INSTALL_DIR} -DBUILD_DOXYGEN_DOCS=OFF -DBUILD_MANUAL=OFF -DENABLE_DIST=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF)


ExternalProject_Add(viennacl
  PREFIX ${VIENNACL_PREFIX}
  GIT_REPOSITORY https://github.com/viennacl/viennacl-dev.git
  GIT_TAG master
  CMAKE_ARGS ${VIENNACL_CMAKE_ARGS}
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_COMMAND ""
)
