set(VIENNAMESH_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/viennamesh")
set(VIENNAMESH_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/viennamesh/install")
SET(VIENNAMESH_CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${VIENNAMESH_INSTALL_DIR} 
    -DBUILD_DOXYGEN_DOCS=OFF -DBUILD_MANUAL=OFF -DENABLE_DIST=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TOOLS=OFF -DBUILD_TESTING=OFF
    -DBUILD_EXTERNAL_LIB_TRIANGLE=ON -DBUILD_EXTERNAL_LIB_TETGEN=OFF -DBUILD_EXTERNAL_LIB_NETGEN=OFF -DBUILD_EXTERNAL_LIB_VGMODELER=OFF)


ExternalProject_Add(viennamesh
  PREFIX ${VIENNAMESH_PREFIX}
  GIT_REPOSITORY https://github.com/viennamesh/viennamesh-dev.git
  GIT_TAG master
  CMAKE_ARGS ${VIENNAMESH_CMAKE_ARGS}
  INSTALL_COMMAND ""
)
