set(VIENNAMATERIALS_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/viennamaterials")
set(VIENNAMATERIALS_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/viennamaterials/install")
set(VIENNAMATERIALS_CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${VIENNAMATERIALS_INSTALL_DIR} -DBUILD_EXAMPLES=OFF -DBUILD_DTD_CHECK_SUPPORT=OFF -DBUILD_SERIALIZATION=OFF)


ExternalProject_Add(viennamaterials
  PREFIX ${VIENNAMATERIALS_PREFIX}
  GIT_REPOSITORY https://github.com/viennamaterials/viennamaterials-dev.git
  GIT_TAG devel
  CMAKE_ARGS ${VIENNAMATERIALS_CMAKE_ARGS}
  INSTALL_COMMAND ""
)
